-- HSK Word Database Seed
-- This will populate the database with HSK 1-6 vocabulary

-- HSK 1 Words (150 words) - Most basic level
INSERT INTO "Word" ("hanzi", "pinyin", "translation", "hskLevel", "category", "audioUrl", "exampleSentence") VALUES

-- Numbers
('一', 'yī', 'one', 1, 'numbers', null, '我有一个朋友。'),
('二', 'èr', 'two', 1, 'numbers', null, '我有二十块钱。'),
('三', 'sān', 'three', 1, 'numbers', null, '三个人去吃饭。'),
('四', 'sì', 'four', 1, 'numbers', null, '今天是四月。'),
('五', 'wǔ', 'five', 1, 'numbers', null, '五点钟见。'),
('六', 'liù', 'six', 1, 'numbers', null, '六月很热。'),
('七', 'qī', 'seven', 1, 'numbers', null, '七点起床。'),
('八', 'bā', 'eight', 1, 'numbers', null, '八个苹果。'),
('九', 'jiǔ', 'nine', 1, 'numbers', null, '九月开学。'),
('十', 'shí', 'ten', 1, 'numbers', null, '十分钟后见。'),

-- Basic verbs
('是', 'shì', 'to be', 1, 'verbs', null, '我是学生。'),
('有', 'yǒu', 'to have', 1, 'verbs', null, '我有一本书。'),
('在', 'zài', 'to be at/in', 1, 'verbs', null, '他在家。'),
('看', 'kàn', 'to see/look', 1, 'verbs', null, '我看电视。'),
('听', 'tīng', 'to listen', 1, 'verbs', null, '听音乐。'),
('说', 'shuō', 'to speak', 1, 'verbs', null, '说中文。'),
('读', 'dú', 'to read', 1, 'verbs', null, '读书。'),
('写', 'xiě', 'to write', 1, 'verbs', null, '写汉字。'),
('吃', 'chī', 'to eat', 1, 'verbs', null, '吃饭。'),
('喝', 'hē', 'to drink', 1, 'verbs', null, '喝水。'),
('买', 'mǎi', 'to buy', 1, 'verbs', null, '买东西。'),
('来', 'lái', 'to come', 1, 'verbs', null, '他来了。'),
('去', 'qù', 'to go', 1, 'verbs', null, '去学校。'),
('做', 'zuò', 'to do/make', 1, 'verbs', null, '做作业。'),
('坐', 'zuò', 'to sit', 1, 'verbs', null, '坐下。'),
('住', 'zhù', 'to live', 1, 'verbs', null, '住北京。'),
('叫', 'jiào', 'to be called', 1, 'verbs', null, '我叫小明。'),
('学', 'xué', 'to study/learn', 1, 'verbs', null, '学中文。'),
('认识', 'rènshi', 'to know', 1, 'verbs', null, '认识他。'),
('会', 'huì', 'can/know how', 1, 'verbs', null, '我会说英语。'),
('能', 'néng', 'can/able to', 1, 'verbs', null, '我能帮你。'),
('想', 'xiǎng', 'to want/think', 1, 'verbs', null, '我想吃饭。'),
('爱', 'ài', 'to love', 1, 'verbs', null, '我爱你。'),
('喜欢', 'xǐhuan', 'to like', 1, 'verbs', null, '我喜欢猫。'),
('工作', 'gōngzuò', 'to work', 1, 'verbs', null, '他在工作。'),

-- Pronouns
('我', 'wǒ', 'I/me', 1, 'pronouns', null, '我是学生。'),
('你', 'nǐ', 'you', 1, 'pronouns', null, '你好。'),
('他', 'tā', 'he/him', 1, 'pronouns', null, '他很高。'),
('她', 'tā', 'she/her', 1, 'pronouns', null, '她很漂亮。'),
('我们', 'wǒmen', 'we/us', 1, 'pronouns', null, '我们是朋友。'),
('你们', 'nǐmen', 'you (plural)', 1, 'pronouns', null, '你们好。'),
('他们', 'tāmen', 'they/them', 1, 'pronouns', null, '他们来了。'),
('这', 'zhè', 'this', 1, 'pronouns', null, '这是书。'),
('那', 'nà', 'that', 1, 'pronouns', null, '那是他的。'),
('什么', 'shénme', 'what', 1, 'pronouns', null, '这是什么？'),
('谁', 'shéi', 'who', 1, 'pronouns', null, '他是谁？'),
('哪', 'nǎ', 'which', 1, 'pronouns', null, '哪个好？'),

-- Common nouns
('人', 'rén', 'person', 1, 'nouns', null, '他是好人。'),
('朋友', 'péngyou', 'friend', 1, 'nouns', null, '我的朋友。'),
('学生', 'xuésheng', 'student', 1, 'nouns', null, '他是学生。'),
('老师', 'lǎoshī', 'teacher', 1, 'nouns', null, '中文老师。'),
('医生', 'yīshēng', 'doctor', 1, 'nouns', null, '他是医生。'),
('爸爸', 'bàba', 'father/dad', 1, 'nouns', null, '我爸爸。'),
('妈妈', 'māma', 'mother/mom', 1, 'nouns', null, '我妈妈。'),
('儿子', 'érzi', 'son', 1, 'nouns', null, '我儿子。'),
('女儿', 'nǚér', 'daughter', 1, 'nouns', null, '他女儿。'),
('猫', 'māo', 'cat', 1, 'nouns', null, '一只猫。'),
('狗', 'gǒu', 'dog', 1, 'nouns', null, '两只狗。'),
('书', 'shū', 'book', 1, 'nouns', null, '一本书。'),
('电影', 'diànyǐng', 'movie', 1, 'nouns', null, '看电影。'),
('电视', 'diànshì', 'television', 1, 'nouns', null, '看电视。'),
('电脑', 'diànnǎo', 'computer', 1, 'nouns', null, '用电脑。'),
('手机', 'shǒujī', 'phone', 1, 'nouns', null, '我的手机。'),
('饭', 'fàn', 'food/meal', 1, 'nouns', null, '吃饭。'),
('米饭', 'mǐfàn', 'rice', 1, 'nouns', null, '吃米饭。'),
('面条', 'miàntiáo', 'noodles', 1, 'nouns', null, '吃面条。'),
('水', 'shuǐ', 'water', 1, 'nouns', null, '喝水。'),
('茶', 'chá', 'tea', 1, 'nouns', null, '喝茶。'),
('咖啡', 'kāfēi', 'coffee', 1, 'nouns', null, '喝咖啡。'),
('苹果', 'píngguǒ', 'apple', 1, 'nouns', null, '吃苹果。'),
('菜', 'cài', 'dish/vegetable', 1, 'nouns', null, '吃菜。'),
('钱', 'qián', 'money', 1, 'nouns', null, '多少钱？'),
('时间', 'shíjiān', 'time', 1, 'nouns', null, '几点？'),
('年', 'nián', 'year', 1, 'nouns', null, '今年。'),
('月', 'yuè', 'month', 1, 'nouns', null, '这个月。'),
('日', 'rì', 'day/date', 1, 'nouns', null, '几号？'),
('星期', 'xīngqī', 'week', 1, 'nouns', null, '星期一。'),
('天', 'tiān', 'day/sky', 1, 'nouns', null, '今天。'),
('点', 'diǎn', 'oclock/point', 1, 'nouns', null, '三点。'),
('分钟', 'fēnzhōng', 'minute', 1, 'nouns', null, '五分钟。'),
('家', 'jiā', 'home/family', 1, 'nouns', null, '回家。'),
('学校', 'xuéxiào', 'school', 1, 'nouns', null, '去学校。'),
('医院', 'yīyuàn', 'hospital', 1, 'nouns', null, '在医院。'),
('商店', 'shāngdiàn', 'store/shop', 1, 'nouns', null, '去商店。'),
('饭馆', 'fànguǎn', 'restaurant', 1, 'nouns', null, '去饭馆。'),
('中国', 'Zhōngguó', 'China', 1, 'nouns', null, '去中国。'),
('北京', 'Běijīng', 'Beijing', 1, 'nouns', null, '住北京。'),
('名字', 'míngzi', 'name', 1, 'nouns', null, '你叫什么名字？'),
('汉语', 'Hànyǔ', 'Chinese language', 1, 'nouns', null, '学汉语。'),
('字', 'zì', 'character/word', 1, 'nouns', null, '写汉字。'),
('桌子', 'zhuōzi', 'table/desk', 1, 'nouns', null, '在桌子上。'),
('椅子', 'yǐzi', 'chair', 1, 'nouns', null, '坐椅子。'),
('雨', 'yǔ', 'rain', 1, 'nouns', null, '下雨。'),
('衣服', 'yīfu', 'clothes', 1, 'nouns', null, '买衣服。'),
('飞机', 'fēijī', 'airplane', 1, 'nouns', null, '坐飞机。'),
('出租车', 'chūzūchē', 'taxi', 1, 'nouns', null, '坐出租车。'),

-- Adjectives
('好', 'hǎo', 'good', 1, 'adjectives', null, '很好。'),
('大', 'dà', 'big', 1, 'adjectives', null, '很大。'),
('小', 'xiǎo', 'small', 1, 'adjectives', null, '很小。'),
('多', 'duō', 'many/much', 1, 'adjectives', null, '很多人。'),
('少', 'shǎo', 'few/little', 1, 'adjectives', null, '很少。'),
('高', 'gāo', 'tall/high', 1, 'adjectives', null, '很高。'),
('冷', 'lěng', 'cold', 1, 'adjectives', null, '很冷。'),
('热', 'rè', 'hot', 1, 'adjectives', null, '很热。'),
('漂亮', 'piàoliang', 'beautiful', 1, 'adjectives', null, '很漂亮。'),
('贵', 'guì', 'expensive', 1, 'adjectives', null, '太贵了。'),
('便宜', 'piányi', 'cheap', 1, 'adjectives', null, '很便宜。'),

-- Adverbs & Others
('不', 'bù', 'not/no', 1, 'adverbs', null, '不是。'),
('没', 'méi', 'not have', 1, 'adverbs', null, '没有。'),
('很', 'hěn', 'very', 1, 'adverbs', null, '很好。'),
('太', 'tài', 'too', 1, 'adverbs', null, '太热了。'),
('都', 'dōu', 'all/both', 1, 'adverbs', null, '都是。'),
('也', 'yě', 'also', 1, 'adverbs', null, '我也是。'),
('再', 'zài', 'again', 1, 'adverbs', null, '再见。'),
('现在', 'xiànzài', 'now', 1, 'adverbs', null, '现在几点？'),
('今天', 'jīntiān', 'today', 1, 'adverbs', null, '今天星期几？'),
('明天', 'míngtiān', 'tomorrow', 1, 'adverbs', null, '明天见。'),
('昨天', 'zuótiān', 'yesterday', 1, 'adverbs', null, '昨天去了。'),
('上', 'shàng', 'up/on', 1, 'adverbs', null, '在桌子上。'),
('下', 'xià', 'down/below', 1, 'adverbs', null, '在桌子下。'),
('前', 'qián', 'front/before', 1, 'adverbs', null, '前面。'),
('后', 'hòu', 'back/after', 1, 'adverbs', null, '后面。'),
('里', 'lǐ', 'inside', 1, 'adverbs', null, '在家里。'),
('这里', 'zhèlǐ', 'here', 1, 'adverbs', null, '在这里。'),
('那里', 'nàlǐ', 'there', 1, 'adverbs', null, '在那里。'),
('哪里', 'nǎlǐ', 'where', 1, 'adverbs', null, '你在哪里？'),

-- Common phrases
('你好', 'nǐ hǎo', 'hello', 1, 'phrases', null, '你好！'),
('谢谢', 'xièxie', 'thank you', 1, 'phrases', null, '谢谢你！'),
('再见', 'zàijiàn', 'goodbye', 1, 'phrases', null, '再见！'),
('对不起', 'duìbuqǐ', 'sorry', 1, 'phrases', null, '对不起。'),
('没关系', 'méi guānxi', 'no problem', 1, 'phrases', null, '没关系。'),
('请', 'qǐng', 'please', 1, 'phrases', null, '请坐。'),
('几', 'jǐ', 'how many', 1, 'phrases', null, '几个？'),
('多少', 'duōshao', 'how much/many', 1, 'phrases', null, '多少钱？'),
('怎么', 'zěnme', 'how', 1, 'phrases', null, '怎么样？'),
('怎么样', 'zěnmeyàng', 'how about', 1, 'phrases', null, '怎么样？'),
('吗', 'ma', 'question particle', 1, 'particles', null, '好吗？'),
('呢', 'ne', 'question particle', 1, 'particles', null, '你呢？'),
('的', 'de', 'possessive', 1, 'particles', null, '我的书。'),
('了', 'le', 'completed action', 1, 'particles', null, '吃了。'),
('在', 'zài', 'at/in (progressive)', 1, 'particles', null, '在看书。');

-- HSK 2 Common Words (50 additional examples)
INSERT INTO "Word" ("hanzi", "pinyin", "translation", "hskLevel", "category", "audioUrl", "exampleSentence") VALUES
('开始', 'kāishǐ', 'to start/begin', 2, 'verbs', null, '开始学习。'),
('告诉', 'gàosu', 'to tell', 2, 'verbs', null, '告诉我。'),
('帮助', 'bāngzhù', 'to help', 2, 'verbs', null, '帮助别人。'),
('问', 'wèn', 'to ask', 2, 'verbs', null, '问问题。'),
('回答', 'huídá', 'to answer', 2, 'verbs', null, '回答问题。'),
('介绍', 'jièshào', 'to introduce', 2, 'verbs', null, '介绍朋友。'),
('准备', 'zhǔnbèi', 'to prepare', 2, 'verbs', null, '准备考试。'),
('觉得', 'juéde', 'to feel/think', 2, 'verbs', null, '我觉得很好。'),
('知道', 'zhīdào', 'to know', 2, 'verbs', null, '我知道了。'),
('忘记', 'wàngjì', 'to forget', 2, 'verbs', null, '忘记了。'),
('记得', 'jìde', 'to remember', 2, 'verbs', null, '我记得。'),
('起床', 'qǐchuáng', 'to get up', 2, 'verbs', null, '早上起床。'),
('睡觉', 'shuìjiào', 'to sleep', 2, 'verbs', null, '晚上睡觉。'),
('洗', 'xǐ', 'to wash', 2, 'verbs', null, '洗手。'),
('穿', 'chuān', 'to wear', 2, 'verbs', null, '穿衣服。'),
('跑步', 'pǎobù', 'to jog/run', 2, 'verbs', null, '去跑步。'),
('游泳', 'yóuyǒng', 'to swim', 2, 'verbs', null, '去游泳。'),
('唱歌', 'chànggē', 'to sing', 2, 'verbs', null, '唱歌很好听。'),
('跳舞', 'tiàowǔ', 'to dance', 2, 'verbs', null, '跳舞很开心。'),
('打篮球', 'dǎ lánqiú', 'to play basketball', 2, 'verbs', null, '打篮球。'),
('踢足球', 'tī zúqiú', 'to play football', 2, 'verbs', null, '踢足球。'),

('身体', 'shēntǐ', 'body', 2, 'nouns', null, '身体健康。'),
('眼睛', 'yǎnjing', 'eye', 2, 'nouns', null, '大眼睛。'),
('耳朵', 'ěrduo', 'ear', 2, 'nouns', null, '听不见。'),
('嘴', 'zuǐ', 'mouth', 2, 'nouns', null, '张嘴。'),
('手', 'shǒu', 'hand', 2, 'nouns', null, '洗手。'),
('脚', 'jiǎo', 'foot', 2, 'nouns', null, '走路。'),
('头', 'tóu', 'head', 2, 'nouns', null, '头疼。'),
('脸', 'liǎn', 'face', 2, 'nouns', null, '洗脸。'),
('颜色', 'yánsè', 'color', 2, 'nouns', null, '什么颜色？'),
('红色', 'hóngsè', 'red', 2, 'nouns', null, '红色的。'),
('白色', 'báisè', 'white', 2, 'nouns', null, '白色的。'),
('黑色', 'hēisè', 'black', 2, 'nouns', null, '黑色的。'),
('黄色', 'huángsè', 'yellow', 2, 'nouns', null, '黄色的。'),
('蓝色', 'lánsè', 'blue', 2, 'nouns', null, '蓝色的。'),
('绿色', 'lǜsè', 'green', 2, 'nouns', null, '绿色的。'),

('快', 'kuài', 'fast/quick', 2, 'adjectives', null, '很快。'),
('慢', 'màn', 'slow', 2, 'adjectives', null, '很慢。'),
('新', 'xīn', 'new', 2, 'adjectives', null, '新的。'),
('旧', 'jiù', 'old', 2, 'adjectives', null, '旧的。'),
('累', 'lèi', 'tired', 2, 'adjectives', null, '很累。'),
('饿', 'è', 'hungry', 2, 'adjectives', null, '很饿。'),
('渴', 'kě', 'thirsty', 2, 'adjectives', null, '很渴。'),
('高兴', 'gāoxìng', 'happy', 2, 'adjectives', null, '很高兴。'),
('生气', 'shēngqì', 'angry', 2, 'adjectives', null, '生气了。'),

('常常', 'chángcháng', 'often', 2, 'adverbs', null, '常常来。'),
('已经', 'yǐjīng', 'already', 2, 'adverbs', null, '已经吃了。'),
('还', 'hái', 'still/also', 2, 'adverbs', null, '还有。'),
('一起', 'yìqǐ', 'together', 2, 'adverbs', null, '一起去。'),
('可能', 'kěnéng', 'maybe', 2, 'adverbs', null, '可能下雨。');

-- Note: This is a subset. A complete HSK database would include:
-- HSK 1: 150 words
-- HSK 2: 150 words (total 300)
-- HSK 3: 300 words (total 600)
-- HSK 4: 600 words (total 1200)
-- HSK 5: 1300 words (total 2500)
-- HSK 6: 2500 words (total 5000)
